// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.0
// source: pkg/mq/message_header.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageHeader mq消息头
type MessageHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tag message tag
	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	// unique_id 全局唯一id，用于防止重复消费，保证幂等性
	UniqueId string `protobuf:"bytes,2,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	// body_protocol 消息体body序列化协议
	BodyProtocol Protocol `protobuf:"varint,3,opt,name=body_protocol,json=bodyProtocol,proto3,enum=pkg.mq.Protocol" json:"body_protocol,omitempty"`
}

func (x *MessageHeader) Reset() {
	*x = MessageHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_mq_message_header_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeader) ProtoMessage() {}

func (x *MessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mq_message_header_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeader.ProtoReflect.Descriptor instead.
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return file_pkg_mq_message_header_proto_rawDescGZIP(), []int{0}
}

func (x *MessageHeader) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *MessageHeader) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *MessageHeader) GetBodyProtocol() Protocol {
	if x != nil {
		return x.BodyProtocol
	}
	return Protocol_PROTOCOL_INVALID
}

var File_pkg_mq_message_header_proto protoreflect.FileDescriptor

var file_pkg_mq_message_header_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x71, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70,
	0x6b, 0x67, 0x2e, 0x6d, 0x71, 0x1a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x71, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x0d,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12,
	0x1b, 0x0a, 0x09, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x0d,
	0x62, 0x6f, 0x64, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x6d, 0x71, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x0c, 0x62, 0x6f, 0x64, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x42, 0x35, 0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2e, 0x6d, 0x71, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x42, 0x12, 0x50, 0x6b,
	0x67, 0x4d, 0x71, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x50, 0x01, 0x5a, 0x06, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_mq_message_header_proto_rawDescOnce sync.Once
	file_pkg_mq_message_header_proto_rawDescData = file_pkg_mq_message_header_proto_rawDesc
)

func file_pkg_mq_message_header_proto_rawDescGZIP() []byte {
	file_pkg_mq_message_header_proto_rawDescOnce.Do(func() {
		file_pkg_mq_message_header_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_mq_message_header_proto_rawDescData)
	})
	return file_pkg_mq_message_header_proto_rawDescData
}

var file_pkg_mq_message_header_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_mq_message_header_proto_goTypes = []interface{}{
	(*MessageHeader)(nil), // 0: pkg.mq.MessageHeader
	(Protocol)(0),         // 1: pkg.mq.Protocol
}
var file_pkg_mq_message_header_proto_depIdxs = []int32{
	1, // 0: pkg.mq.MessageHeader.body_protocol:type_name -> pkg.mq.Protocol
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_mq_message_header_proto_init() }
func file_pkg_mq_message_header_proto_init() {
	if File_pkg_mq_message_header_proto != nil {
		return
	}
	file_pkg_mq_protocol_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pkg_mq_message_header_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_mq_message_header_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_mq_message_header_proto_goTypes,
		DependencyIndexes: file_pkg_mq_message_header_proto_depIdxs,
		MessageInfos:      file_pkg_mq_message_header_proto_msgTypes,
	}.Build()
	File_pkg_mq_message_header_proto = out.File
	file_pkg_mq_message_header_proto_rawDesc = nil
	file_pkg_mq_message_header_proto_goTypes = nil
	file_pkg_mq_message_header_proto_depIdxs = nil
}
