// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.0
// source: pkg/mq/protocol.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Protocol 协议
type Protocol int32

const (
	// PROTOCOL_INVALID invalid protocol
	Protocol_PROTOCOL_INVALID Protocol = 0
	// PROTOCOL_PROTOBUF protobuf protocol
	Protocol_PROTOCOL_PROTOBUF Protocol = 1
	// PROTOCOL_JSON json protocol
	Protocol_PROTOCOL_JSON Protocol = 2
	// PROTOCOL_STRING body as string and not use protocol to serialize
	Protocol_PROTOCOL_STRING Protocol = 3
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_INVALID",
		1: "PROTOCOL_PROTOBUF",
		2: "PROTOCOL_JSON",
		3: "PROTOCOL_STRING",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_INVALID":  0,
		"PROTOCOL_PROTOBUF": 1,
		"PROTOCOL_JSON":     2,
		"PROTOCOL_STRING":   3,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_mq_protocol_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_pkg_mq_protocol_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_pkg_mq_protocol_proto_rawDescGZIP(), []int{0}
}

var File_pkg_mq_protocol_proto protoreflect.FileDescriptor

var file_pkg_mq_protocol_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x71, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x6b, 0x67, 0x2e, 0x6d, 0x71, 0x2a,
	0x5f, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x10, 0x50,
	0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10,
	0x00, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x50, 0x52,
	0x4f, 0x54, 0x4f, 0x42, 0x55, 0x46, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x52, 0x4f, 0x54,
	0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x4a, 0x53, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x50,
	0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x03,
	0x42, 0x2a, 0x0a, 0x0f, 0x70, 0x6b, 0x67, 0x2e, 0x6d, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x42, 0x0d, 0x50, 0x6b, 0x67, 0x4d, 0x71, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x50, 0x01, 0x5a, 0x06, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x71, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_mq_protocol_proto_rawDescOnce sync.Once
	file_pkg_mq_protocol_proto_rawDescData = file_pkg_mq_protocol_proto_rawDesc
)

func file_pkg_mq_protocol_proto_rawDescGZIP() []byte {
	file_pkg_mq_protocol_proto_rawDescOnce.Do(func() {
		file_pkg_mq_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_mq_protocol_proto_rawDescData)
	})
	return file_pkg_mq_protocol_proto_rawDescData
}

var file_pkg_mq_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_mq_protocol_proto_goTypes = []interface{}{
	(Protocol)(0), // 0: pkg.mq.Protocol
}
var file_pkg_mq_protocol_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_mq_protocol_proto_init() }
func file_pkg_mq_protocol_proto_init() {
	if File_pkg_mq_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_mq_protocol_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_mq_protocol_proto_goTypes,
		DependencyIndexes: file_pkg_mq_protocol_proto_depIdxs,
		EnumInfos:         file_pkg_mq_protocol_proto_enumTypes,
	}.Build()
	File_pkg_mq_protocol_proto = out.File
	file_pkg_mq_protocol_proto_rawDesc = nil
	file_pkg_mq_protocol_proto_goTypes = nil
	file_pkg_mq_protocol_proto_depIdxs = nil
}
