// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.0
// source: gong/protobuf/api/product/request/test_nsq.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetProductDetailRequest ...
type GetProductDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// product_id ..
	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	// name_space nnn
	NameSpace string `protobuf:"bytes,2,opt,name=name_space,json=nameSpace,proto3" json:"name_space,omitempty"`
	// one_field aaa
	//
	// Types that are assignable to OneField:
	//	*GetProductDetailRequest_UserName
	//	*GetProductDetailRequest_MemberName
	OneField isGetProductDetailRequest_OneField `protobuf_oneof:"one_field"`
	// map_info ...
	MapInfo map[string]int64 `protobuf:"bytes,5,rep,name=map_info,json=mapInfo,proto3" json:"map_info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *GetProductDetailRequest) Reset() {
	*x = GetProductDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gong_protobuf_api_product_request_get_product_detail_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDetailRequest) ProtoMessage() {}

func (x *GetProductDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gong_protobuf_api_product_request_get_product_detail_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDetailRequest.ProtoReflect.Descriptor instead.
func (*GetProductDetailRequest) Descriptor() ([]byte, []int) {
	return file_gong_protobuf_api_product_request_get_product_detail_request_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductDetailRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetProductDetailRequest) GetNameSpace() string {
	if x != nil {
		return x.NameSpace
	}
	return ""
}

func (m *GetProductDetailRequest) GetOneField() isGetProductDetailRequest_OneField {
	if m != nil {
		return m.OneField
	}
	return nil
}

func (x *GetProductDetailRequest) GetUserName() string {
	if x, ok := x.GetOneField().(*GetProductDetailRequest_UserName); ok {
		return x.UserName
	}
	return ""
}

func (x *GetProductDetailRequest) GetMemberName() string {
	if x, ok := x.GetOneField().(*GetProductDetailRequest_MemberName); ok {
		return x.MemberName
	}
	return ""
}

func (x *GetProductDetailRequest) GetMapInfo() map[string]int64 {
	if x != nil {
		return x.MapInfo
	}
	return nil
}

type isGetProductDetailRequest_OneField interface {
	isGetProductDetailRequest_OneField()
}

type GetProductDetailRequest_UserName struct {
	// user_name ..
	UserName string `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3,oneof"`
}

type GetProductDetailRequest_MemberName struct {
	// member_name ...
	MemberName string `protobuf:"bytes,4,opt,name=member_name,json=memberName,proto3,oneof"`
}

func (*GetProductDetailRequest_UserName) isGetProductDetailRequest_OneField() {}

func (*GetProductDetailRequest_MemberName) isGetProductDetailRequest_OneField() {}

var File_gong_protobuf_api_product_request_get_product_detail_request_proto protoreflect.FileDescriptor

var file_gong_protobuf_api_product_request_get_product_detail_request_proto_rawDesc = []byte{
	0x0a, 0x42, 0x67, 0x6f, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x67, 0x6f, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x22, 0xb2, 0x02, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1d, 0x0a,
	0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0b,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x4e, 0x0a, 0x08, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x33, 0x2e, 0x67, 0x6f, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x6d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x3a, 0x0a, 0x0c, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x6f,
	0x6e, 0x65, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x1e, 0x5a, 0x1c, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gong_protobuf_api_product_request_get_product_detail_request_proto_rawDescOnce sync.Once
	file_gong_protobuf_api_product_request_get_product_detail_request_proto_rawDescData = file_gong_protobuf_api_product_request_get_product_detail_request_proto_rawDesc
)

func file_gong_protobuf_api_product_request_get_product_detail_request_proto_rawDescGZIP() []byte {
	file_gong_protobuf_api_product_request_get_product_detail_request_proto_rawDescOnce.Do(func() {
		file_gong_protobuf_api_product_request_get_product_detail_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_gong_protobuf_api_product_request_get_product_detail_request_proto_rawDescData)
	})
	return file_gong_protobuf_api_product_request_get_product_detail_request_proto_rawDescData
}

var file_gong_protobuf_api_product_request_get_product_detail_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gong_protobuf_api_product_request_get_product_detail_request_proto_goTypes = []interface{}{
	(*GetProductDetailRequest)(nil), // 0: gong.protobuf.GetProductDetailRequest
	nil,                             // 1: gong.protobuf.GetProductDetailRequest.MapInfoEntry
}
var file_gong_protobuf_api_product_request_get_product_detail_request_proto_depIdxs = []int32{
	1, // 0: gong.protobuf.GetProductDetailRequest.map_info:type_name -> gong.protobuf.GetProductDetailRequest.MapInfoEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gong_protobuf_api_product_request_get_product_detail_request_proto_init() }
func file_gong_protobuf_api_product_request_get_product_detail_request_proto_init() {
	if File_gong_protobuf_api_product_request_get_product_detail_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gong_protobuf_api_product_request_get_product_detail_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProductDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_gong_protobuf_api_product_request_get_product_detail_request_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*GetProductDetailRequest_UserName)(nil),
		(*GetProductDetailRequest_MemberName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gong_protobuf_api_product_request_get_product_detail_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gong_protobuf_api_product_request_get_product_detail_request_proto_goTypes,
		DependencyIndexes: file_gong_protobuf_api_product_request_get_product_detail_request_proto_depIdxs,
		MessageInfos:      file_gong_protobuf_api_product_request_get_product_detail_request_proto_msgTypes,
	}.Build()
	File_gong_protobuf_api_product_request_get_product_detail_request_proto = out.File
	file_gong_protobuf_api_product_request_get_product_detail_request_proto_rawDesc = nil
	file_gong_protobuf_api_product_request_get_product_detail_request_proto_goTypes = nil
	file_gong_protobuf_api_product_request_get_product_detail_request_proto_depIdxs = nil
}
